version: '3.8'

services:
  app:
    image: 'webdevops/php:8.2'
    volumes:
      - ./:/app
    ports: 
      - 8080:80
    working_dir: /app
    entrypoint: 'php artisan serv --host=0.0.0.0 --port=80'


